name: Build Web Develop
permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - develop
  workflow_dispatch:

concurrency:
  group: "web-develop"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./flutter_app
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.9'
          channel: 'stable'
          cache: true
      - run: flutter pub get
      - run: flutter build web --base-href '/flutter_playground/'
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./flutter_app/build/web/
      - id: deployment
        uses: actions/deploy-pages@v2
