name: Build Android Develop
permissions:
  contents: read

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./flutter_app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.9'
          channel: 'stable'
          cache: true
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle
      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: development-apk
          path: ./flutter_app/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 3
