name: Lint
permissions:
  contents: read

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/**
      - flutter_app/**
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./flutter_app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.9'
          channel: 'stable'
          cache: true
      - run: flutter pub get
      - run: echo "::add-matcher::.github/analyzer-problem-matcher.json"
      - run: flutter analyze
